name: Bash CI Pipeline

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  test-cleaner:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Force a failure when commit message contains [fail]
      - name: Force failure on [fail]
        if: contains(github.event.head_commit.message, '[fail]')
        run: |
          echo "❌ Failing intentionally because commit message contains [fail]"
          exit 1

      # 3️⃣ Validate syntax of all shell scripts
      - name: Check Bash syntax
        run: |
          echo "🔍 Checking syntax for all .sh files..."
          find . -type f -name "*.sh" -exec bash -n {} \;

      # 4️⃣ Run Cleaner.sh safely (smoke test)
      - name: Run Cleaner.sh (dry run)
        run: |
          echo "⚙️ Testing Cleaner.sh..."
          chmod +x ./Cleaner.sh
          ./Cleaner.sh --help || true

      # 5️⃣ Verify help output (this one will fail if missing 'Usage:')
      - name: Verify help text
        run: |
          echo "🧪 Checking help output for 'Usage:' keyword..."
          out="$(./Cleaner.sh --help || true)"
          echo "$out"
          echo "$out" | grep -q "Usage:" || { echo "❌ Expected 'Usage:' in help output"; exit 1; }

      # 6️⃣ Always upload workspace files (useful for debugging)
      - name: Upload workspace
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cleaner-workspace
          path: ./
