name: Bash CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-cleaner:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Validate syntax of all shell scripts
      - name: Check Bash syntax
        run: |
          echo "🔍 Checking syntax for all .sh files..."
          find . -type f -name "*.sh" -exec bash -n {} \;

      # 3️⃣ Run Cleaner.sh safely
      - name: Run Cleaner.sh (dry run)
        run: |
          echo "⚙️ Testing Cleaner.sh..."
          chmod +x ./Cleaner.sh
          ./Cleaner.sh --help || true

      # 4️⃣ Show repo structure (optional)
      - name: List workspace
        run: ls -la

      # 5️⃣ Verify help text
      - name: Verify help text
        run: |
          set -euo pipefail
          chmod +x ./Cleaner.sh
          out="$(./Cleaner.sh --help || true)"
          echo "$out"
          echo "$out" | grep -q "Usage:" || { echo "❌ Expected 'Usage:' in --help"; exit 1; }

      # 6️⃣ Example of forcing a failure based on commit message
      - name: Force failure when commit message contains [fail]
        if: contains(github.event.head_commit.message, '[fail]')
        run: |
          echo "Failing on purpose because commit message contains [fail]"
          exit 1

      - name: Upload artifacts (even on failure)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cleaner-dist
          path: |
            dist/**
            **/*.log